apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://13.60.5.209:3306/user_management"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
  JWT_EXPIRATION: "86400000"
  AWS_S3_BUCKET_NAME: "amzn-proj0131-syn-buckett"
  AWS_S3_REGION: "us-west-2"
  CORS_ALLOWED_ORIGINS: "http://localhost:4200"
