apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://13.60.5.209:3306/users"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
  JWT_EXPIRATION: "86400000"
  AWS_S3_BUCKET_NAME: "user-123-management"
  AWS_S3_REGION: "eu-north-1"
  CORS_ALLOWED_ORIGINS: "http://localhost:4200"
