---
- name: Deploy Angular Application
  hosts: frontend
  become: yes

  vars:
    web_root: /var/www/html
    backend_ip: "{{ groups['backend'][0] }}"
    dist_path: "../../../frontend/dist"

  tasks:
    - name: Detect Angular dist folder
      find:
        paths: "{{ dist_path }}"
        file_type: directory
        depth: 1
      register: dist_dirs

    - name: Set Angular dist directory
      set_fact:
        angular_dist: "{{ dist_dirs.files[0].path }}/browser"

    - name: Remove existing web root
      file:
        path: "{{ web_root }}"
        state: absent

    - name: Recreate web root
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Copy Angular files from Jenkins to frontend server
      copy:
        src: "{{ angular_dist }}/"
        dest: "{{ web_root }}/"
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Configure Nginx with API proxy
      copy:
        dest: /etc/nginx/sites-available/angular-app
        content: |
          server {
              listen 80;
              server_name _;

              root {{ web_root }};
              index index.html;

              location /api/ {
                  proxy_pass http://{{ backend_ip }}:8080;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location / {
                  try_files $uri $uri/ /index.html;
              }
          }

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/angular-app
        dest: /etc/nginx/sites-enabled/angular-app
        state: link
        force: yes

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
